version = 0.1

[default.deploy.parameters]
stack_name = "serviceforge-ai"
resolve_s3 = true
s3_prefix = "serviceforge-ai"
region = "ap-south-1"
profile = "serviceforge-dev"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"prod\" TableName=\"ServiceForge\" BedrockModelId=\"amazon.nova-2-lite-v1:0\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
